const KEY = 'regoTraining.v2';
let state = {lessons:{},scores:{}};
try { const saved=JSON.parse(localStorage.getItem(KEY)); if(saved && typeof saved.lessons==='object' && saved.lessons && typeof saved.scores==='object' && saved.scores) state=saved; } catch {}
let currentPage='inicio', quiz=null, toastTimer;
const content=document.getElementById('content');
const names={inicio:'Início',treinamentos:'Treinamentos',progresso:'Meu progresso',avaliacoes:'Avaliações',ajuda:'Ajuda'};
function readCount(m){return Math.min(m.lessons.length,Math.max(0,Number(state.lessons[m.id])||0));}
function passed(m){return Number.isFinite(state.scores[m.id]) && state.scores[m.id]>=70;}
function percent(m){return Math.round((readCount(m)+(passed(m)?1:0))/(m.lessons.length+1)*100);}
function overall(){return Math.round(modules.reduce((sum,m)=>sum+percent(m),0)/modules.length);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{notify('Não foi possível salvar neste navegador. Mantenha esta página aberta.');}}
function notify(message){clearTimeout(toastTimer);const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),4000);}
function bar(value){return `<div class="progress" role="progressbar" aria-label="Progresso" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${value}"><div style="width:${value}%"></div></div>`;}
function status(m){return percent(m)===100?'Concluído':percent(m)>0?'Em andamento':'Não iniciado';}
function card(m,i){return `<article class="card module"><div class="module-top"><div class="module-icon">${m.icon}</div><span class="tag ${percent(m)===100?'done':''}">${status(m)}</span></div><small class="module-number">MÓDULO 0${i+1}</small><h3>${m.title}</h3><p>${m.desc}</p>${bar(percent(m))}<div class="progress-row"><span>${m.duration} min · ${m.lessons.length} aulas</span><b>${percent(m)}%</b></div><button class="btn btn-light course-action" onclick="openCourse('${m.id}')">${percent(m)===100?'Revisar módulo':'Acessar treinamento'} →</button></article>`;}
function home(){const next=modules.find(m=>percent(m)<100)||modules[0];content.innerHTML=`<div class="section-head intro"><span>SUA JORNADA DE APRENDIZAGEM</span><span class="demo-label">Ambiente de demonstração</span></div><section class="hero"><div><div class="eyebrow">AUTO POSTO REGO & CIA</div><h1>Um bom atendimento<br>começa com preparo.</h1><p>Aprenda as rotinas do posto, pratique seus conhecimentos e acompanhe cada conquista.</p><button class="btn btn-primary hero-cta" onclick="openCourse('${next.id}')">${overall()?'Continuar aprendendo':'Começar minha jornada'} →</button></div><div class="hero-art" aria-hidden="true"><div class="pump"></div><span>PREPARO QUE FAZ<br>A DIFERENÇA.</span></div></section><div class="stats">${[['Progresso geral',overall()+'%','◔'],['Módulos concluídos',modules.filter(m=>percent(m)===100).length+'/4','✓'],['Conteúdo disponível','65 min','◷'],['Avaliações aprovadas',modules.filter(passed).length+'/4','★']].map(([label,value,icon])=>`<div class="card stat"><div><div class="stat-label">${label}</div><div class="stat-value">${value}</div></div><div class="stat-icon">${icon}</div></div>`).join('')}</div><div class="section-head"><h2>Sua trilha de capacitação</h2><span>Do primeiro contato ao fechamento</span></div><div class="grid"><div class="modules">${modules.map(card).join('')}</div><aside class="card side-card"><span class="eyebrow">UM PASSO DE CADA VEZ</span><h3>Seu próximo objetivo</h3><div class="donut" style="--value:${overall()}%"><span>${overall()}%<small>da trilha</small></span></div><p>Leia as três aulas de cada módulo e alcance pelo menos 70% na avaliação para concluir.</p><div class="next-step"><strong>${next.title}</strong><p>${readCount(next)} de 3 aulas lidas</p></div><button class="btn btn-light course-action" onclick="navigate('progresso')">Acompanhar meu progresso →</button></aside></div>`;}
function trainings(){content.innerHTML=heading('Treinamentos','Quatro módulos para desenvolver sua rotina profissional.')+`<div class="course-grid">${modules.map(card).join('')}</div>`;}
function heading(title,desc){return `<div class="page-title"><div class="eyebrow">REGO TREINA</div><h1>${title}</h1><p>${desc}</p></div>`;}
function progressPage(){content.innerHTML=heading('Meu progresso','Cada etapa concluída conta. Seu avanço fica salvo neste navegador.')+`<div class="card table-card"><table><thead><tr><th>Módulo</th><th>Aulas lidas</th><th>Progresso</th><th>Melhor nota</th><th>Status</th></tr></thead><tbody>${modules.map(m=>`<tr><td>${m.title}</td><td>${readCount(m)}/3</td><td>${bar(percent(m))}${percent(m)}%</td><td>${Number.isFinite(state.scores[m.id])?state.scores[m.id]+'%':'—'}</td><td>${status(m)}</td></tr>`).join('')}</tbody></table></div><p class="footnote">As notas são de atividades introdutórias e não constituem certificação profissional.</p><button class="btn btn-primary" onclick="window.print()">Imprimir relatório</button>`;}
function evaluations(){content.innerHTML=heading('Avaliações','Responda às três questões de cada módulo. Aprovação a partir de 70%.')+`<div class="course-grid">${modules.map(m=>`<article class="card module"><div class="module-icon">${m.icon}</div><h3>${m.title}</h3><p>${Number.isFinite(state.scores[m.id])?'Melhor resultado: '+state.scores[m.id]+'%':'Você ainda não fez esta avaliação.'}</p><button class="btn btn-primary" onclick="openQuiz('${m.id}')">${Number.isFinite(state.scores[m.id])?'Tentar novamente':'Iniciar avaliação'} →</button></article>`).join('')}</div>`;}
function help(){content.innerHTML=heading('Como podemos ajudar?','Orientações para aproveitar sua jornada de aprendizagem.')+`<div class="help-grid">${[['Como concluo um módulo?','Leia as três aulas e obtenha pelo menos 70% na avaliação. Você pode refazer a avaliação; sua melhor nota fica salva.'],['Onde meu progresso fica salvo?','Neste navegador e dispositivo. Limpar os dados do navegador remove o histórico. Esta demonstração não sincroniza os resultados entre computadores.'],['Posso usar este conteúdo na operação?','O material é uma introdução. Os procedimentos precisam ser validados pelo responsável do posto e acompanhados pela capacitação exigida para cada atividade.'],['Preciso de ajuda com a rotina do posto','Procure o responsável pelo seu turno. Apresente sua dúvida e o módulo relacionado para receber orientação.']].map(([q,a])=>`<details class="card"><summary>${q}</summary><p>${a}</p></details>`).join('')}</div>`;}
function navigate(page){currentPage=names[page]?page:'inicio';document.getElementById('pageTitle').textContent=names[currentPage];document.querySelectorAll('.nav-item').forEach(b=>{b.classList.toggle('active',b.dataset.page===currentPage);b.setAttribute('aria-current',b.dataset.page===currentPage?'page':'false');});({inicio:home,treinamentos:trainings,progresso:progressPage,avaliacoes:evaluations,ajuda:help}[currentPage])();closeMenu();}
function closeMenu(){document.getElementById('sidebar').classList.remove('open');document.getElementById('menuBtn').setAttribute('aria-expanded','false');document.getElementById('menuBackdrop').hidden=true;}
let returnFocus;
function showModal(html){const old=document.getElementById('learningDialog');if(old)old.remove();else returnFocus=document.activeElement;const dialog=document.createElement('dialog');dialog.id='learningDialog';dialog.className='modal';dialog.setAttribute('aria-labelledby','dialogTitle');dialog.innerHTML=`<button class="close" aria-label="Fechar" onclick="closeModal()">×</button>${html}`;document.body.appendChild(dialog);dialog.addEventListener('close',()=>{dialog.remove();returnFocus?.focus();});dialog.showModal();}
function closeModal(){document.getElementById('learningDialog')?.close();}
function openCourse(id,index){const m=modules.find(m=>m.id===id);const step=index??Math.min(readCount(m),m.lessons.length-1);const lesson=m.lessons[step];showModal(`<div class="eyebrow">${m.title} · AULA ${step+1} DE 3</div><h2 id="dialogTitle">${lesson[0]}</h2>${bar(Math.round((step+1)/3*100))}<p class="lesson-copy">${lesson[1]}</p><div class="lesson-tip">Ao final, teste o que aprendeu na avaliação deste módulo.</div><div class="modal-actions"><button class="btn btn-light" ${step===0?'disabled':''} onclick="openCourse('${id}',${step-1})">← Anterior</button><button class="btn btn-primary" onclick="advanceLesson('${id}',${step})">${step===2?'Concluir leitura e avaliar':'Marcar como lida e avançar'} →</button></div>`);}
function advanceLesson(id,step){state.lessons[id]=Math.max(Number(state.lessons[id])||0,step+1);save();navigate(currentPage);if(step<2)openCourse(id,step+1);else openQuiz(id);}
function openQuiz(id){quiz={id,index:0,correct:0};renderQuestion();}
function renderQuestion(){const m=modules.find(m=>m.id===quiz.id),q=m.quiz[quiz.index];showModal(`<div class="eyebrow">${m.title} · QUESTÃO ${quiz.index+1} DE ${m.quiz.length}</div><h2 id="dialogTitle">${q[0]}</h2><div class="answers">${q[1].map((a,i)=>`<button class="quiz-option" onclick="answer(${i})">${a}</button>`).join('')}</div><div id="quizResult" role="status"></div><div id="quizNext"></div>`);}
function answer(choice){const m=modules.find(m=>m.id===quiz.id),q=m.quiz[quiz.index];document.querySelectorAll('.quiz-option').forEach((b,i)=>{b.disabled=true;if(i===q[2])b.classList.add('correct');else if(i===choice)b.classList.add('wrong');});if(choice===q[2])quiz.correct++;document.getElementById('quizResult').textContent=(choice===q[2]?'Resposta correta. ':'Vamos revisar. ')+q[3];document.getElementById('quizNext').innerHTML=`<button class="btn btn-primary" onclick="nextQuestion()">${quiz.index===m.quiz.length-1?'Ver resultado':'Próxima questão'} →</button>`;}
function nextQuestion(){const m=modules.find(m=>m.id===quiz.id);if(++quiz.index<m.quiz.length)return renderQuestion();const score=Math.round(quiz.correct/m.quiz.length*100);state.scores[m.id]=Math.max(state.scores[m.id]||0,score);save();navigate(currentPage);showModal(`<div class="eyebrow">AVALIAÇÃO FINALIZADA</div><h2 id="dialogTitle">${score>=70?'Muito bem!':'Continue praticando.'}</h2><div class="result-score">${score}%</div><p>Você acertou ${quiz.correct} de ${m.quiz.length} questões.</p><p>${score>=70?(readCount(m)===3?'Módulo concluído!':'Avaliação aprovada. Leia todas as aulas para concluir o módulo.'):'Revise o conteúdo e tente novamente. Sua melhor nota será mantida.'}</p><div class="modal-actions"><button class="btn btn-light" onclick="openCourse('${m.id}',0)">Revisar aulas</button><button class="btn btn-primary" onclick="closeModal()">Voltar à plataforma</button></div>`);}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));
document.getElementById('menuBtn').addEventListener('click',()=>{const open=document.getElementById('sidebar').classList.toggle('open');document.getElementById('menuBtn').setAttribute('aria-expanded',String(open));document.getElementById('menuBackdrop').hidden=!open;});
document.getElementById('menuBackdrop').addEventListener('click',closeMenu);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
document.getElementById('notificationBtn').addEventListener('click',()=>notify(modules.filter(m=>percent(m)<100).length+' módulos aguardam sua conclusão.'));
document.getElementById('logoutBtn').addEventListener('click',()=>showModal(`<h2 id="dialogTitle">Recomeçar demonstração?</h2><p>Isso apaga somente as aulas e notas salvas nesta demonstração, neste navegador.</p><div class="modal-actions"><button class="btn btn-light" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" onclick="state={lessons:{},scores:{}};save();closeModal();navigate('inicio')">Apagar e recomeçar</button></div>`));
navigate('inicio');
